### ISSUE TITLE
Set device internal parameters 

### ISSUE THREAD

**Issue by traversaro** [robotology-playground/xsensmt-yarp-driver#7]
To expose the device parameters in the YARP driver, I think we need to edit the deviceclass example provided by Xsens :  https://github.com/robotology-playground/xsensmt-yarp-driver/blob/master/extern/deviceclass.cpp .

**Comment by gabrielenava** [comment]
xsens answered to our question about how to set the IMU parameters:

>XSENS: We do have extensive documentation on the features of the sensor as well as for the Xsens Device API (XDA) and the programming examples available. On a Windows install of MT Software Suite you can find the documentation in the start menu, or you can find the documents here as well: https://base.xsens.com/hc/en-us/articles/207003759-Online-links-to-manuals-from-the-MT-Software-Suite. However please note the "Xsens Device API Library" Windows help file that you'll find in the MT Software Suite in Windows is not on that page and is only in the Windows install of the software. Besides the software development kit, we also provide documentation on all the low level configuration messages in the MT Low Level Communication Protocol Documentation, which you can access directly here: https://xsens.com/download/usermanual/ISM/MT_LowLevelCommunicationProtocol_Documentation.pdf.

I think in the end there are 2 parameters we need to set that are different from the default configuration: the filter profile and the active heading stabilization. The method to call in order to set the first one is `SetFilterProfile` and it can be found at page 48  of the [documentation](https://xsens.com/download/usermanual/ISM/MT_LowLevelCommunicationProtocol_Documentation.pdf).

For enabling the AHS, it seems necessary to use the `SetOptionFlags` method. See pag. 17 of the manual.

May this be an example of application? 

https://github.com/RoboTeamTwente/robot2.0/blob/52f539e434b3be299726e822091c31bce4240b4a/MTi/xbusmessage.h

**Comment by gabrielenava** [comment]
I tried to run the IMU on the real robot with the new configuration parameters and I had issues. In particular, there was an error at startup:

```
733 4,949626 <ERROR> xsensmt: Failing in sending SetOptionFlags message. Aborting.
 
734 4,949693 <UNDEFINED> yarpdev: ***ERROR*** driver <xsensmt> was found but could not open
 
735 4,949715 <ERROR> cannot create device <xsensmt>
 
736 4,949759 <ERROR> ControlBoardWrapper: error while opening subdevice
 
737 4,959701 <UNDEFINED> yarpdev: ***ERROR*** driver <inertial> was found but could not open
 
738 4,959768 <WARNING> Cannot open device xsens_inertial 
```

**Comment by gabrielenava** [comment]
With [this version of the drivers](https://github.com/robotology-playground/xsensmt-yarp-driver/commit/5d2ce0e0a9341d1e29fb4a2ae261c8b4933ff59f) I was able to set the IMU parameters. I verified the parameters are correctly set [here](https://github.com/loc2/element_icub-at-ihmc/issues/50#issuecomment-392000117). A [PR](https://github.com/robotology-playground/xsensmt-yarp-driver/pull/11) is opened. Closing the issue.
